import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const { user, isSignedIn, isLoaded } = useUser();

  if (isLoading) return <div>Loading...</div>;

  // if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {!!isSignedIn && <SignOutButton />}
        {!isSignedIn && <SignInButton />}

        {data?.map((post) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </main>
    </>
  );
}
